name: recipes_app
description: recepies application to explore the flutter development


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/

  fonts:
    - family: Roboto Slab
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf



